### ISSUE TITLE
Unable to setup Development Environment 

### ISSUE THREAD

**Issue by joyosive** [hyperledger-labs/fabric-private-chaincode#545] opened 2021-03-24 01:32 UTC
**Describe the bug**

  Unable to build with Option 1: Using the Docker-based FPC Development Environment

**To Reproduce**

Add steps to reproduce the behavior, e.g.
1. git clone --recursive https://github.com/hyperledger-labs/fabric-private-chaincode.git
2. cd fabric-private-chaincode/
3. cd utils/docker/
4. sudo apt install make
5. make dev 

**Expected behavior**

  Docker container should build

**Log-file**

 `make[2]: Leaving directory '/tmp/intel-sgx-ssl/openssl_source/openssl-1.1.1g'
make -C /tmp/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl/ all
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl'
/opt/intel/sgxsdk/bin/x64/sgx_edger8r --header-only --trusted /tmp/intel-sgx-ssl/Linux/sgx/../package/include//sgx_tsgxssl.edl --search-path /opt/intel/sgxsdk/include
GEN  =>  sgx_tsgxssl_t.c
CXX  <=  tSgxSSL_api.cpp
CXX  <=  tcpu_utils.cpp
CXX  <=  tctype.cpp
tmem_mgmt.cpp: In function 'void* mmap_alloc(size_t)':
tmem_mgmt.cpp:99:24: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
   99 |  catch (std::bad_alloc e) {
      |                        ^
CXX  <=  tmem_mgmt.cpp
tpthread.cpp: In function 'int sgxssl_pthread_rwlock_init(pthread_rwlock_t*, const pthread_rwlockattr_t*)':
tpthread.cpp:83:24: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
   83 |  catch (std::bad_alloc e) {
      |                        ^
tpthread.cpp: In function 'int sgxssl_pthread_key_create(pthread_key_t*, void (*)(void*))':
tpthread.cpp:416:26: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  416 |  } catch (std::bad_alloc e) {
      |                          ^
tpthread.cpp: In function 'int sgxssl_pthread_setspecific(pthread_key_t, const void*)':
tpthread.cpp:537:25: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  537 |   catch (std::bad_alloc e)
      |                         ^
tpthread.cpp:555:24: warning: catching polymorphic type 'class std::bad_alloc' by value [-Wcatch-value=]
  555 |  catch (std::bad_alloc e)
      |                        ^
CXX  <=  tpthread.cpp
CXX  <=  trand.cpp
CXX  <=  tsgxssl_version.cpp
CXX  <=  tsocket.cpp
CXX  <=  tstdio.cpp
CXX  <=  tstdlib.cpp
CXX  <=  tstring.cpp
CXX  <=  ttime.cpp
CXX  <=  tucontext.cpp
CXX  <=  tunistd.cpp
CC  <=  bionic_localtime.c
bionic_sscanf.c: In function 'sgxssl_vsscanf':
bionic_sscanf.c:381:19: warning: array subscript has type 'char' [-Wchar-subscripts]
  381 |     while (ccltab[*str_buf]) {
      |                   ^~~~~~~~
bionic_sscanf.c:395:19: warning: array subscript has type 'char' [-Wchar-subscripts]
  395 |     while (ccltab[*str_buf]) {
      |                   ^~~~~~~~
CC  <=  bionic_sscanf.c
texceptions.c: In function 'setup_cpuinfo':
texceptions.c:130:9: warning: incompatible implicit declaration of built-in function 'memcpy'
  130 |         memcpy(cpuinfo, cpuinfo_table, sizeof(uint32_t)*8*4);
      |         ^~~~~~
texceptions.c:38:1: note: include '<string.h>' or provide a declaration of 'memcpy'
   37 | #include "tcommon.h"
  +++ |+#include <string.h>
   38 | 
CC  <=  texceptions.c
ar rcs libsgx_tsgxssl.a release/tSgxSSL_api.o release/tcpu_utils.o release/tctype.o release/tmem_mgmt.o release/tpthread.o release/trand.o release/tsgxssl_version.o release/tsocket.o release/tstdio.o release/tstdlib.o release/tstring.o release/ttime.o release/tucontext.o release/tunistd.o release/bionic_localtime.o release/bionic_sscanf.o release/texceptions.o  
LINK =>  libsgx_tsgxssl.a
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl'
make -C /tmp/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl/ all
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl'
CC  <=  usgxssl_version.cpp
In file included from utime.cpp:34:
ucommon.h:40: warning: ignoring #pragma warning  [-Wunknown-pragmas]
   40 | #pragma warning( disable: 4100 )
      | 
utime.cpp: In function 'void u_sgxssl_ftime(void*, uint32_t)':
utime.cpp:60:32: warning: 'int ftime(timeb*)' is deprecated [-Wdeprecated-declarations]
   60 |  ftime((struct timeb *) timeptr);
      |                                ^
In file included from utime.cpp:32:
/usr/include/x86_64-linux-gnu/sys/timeb.h:39:12: note: declared here
   39 | extern int ftime (struct timeb *__timebuf)
      |            ^~~~~
utime.cpp:60:32: warning: 'int ftime(timeb*)' is deprecated [-Wdeprecated-declarations]
   60 |  ftime((struct timeb *) timeptr);
      |                                ^
In file included from utime.cpp:32:
/usr/include/x86_64-linux-gnu/sys/timeb.h:39:12: note: declared here
   39 | extern int ftime (struct timeb *__timebuf)
      |            ^~~~~
CC  <=  utime.cpp
ar rcs libsgx_usgxssl.a release/usgxssl_version.o release/utime.o   
LINK =>  libsgx_usgxssl.a
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl'
make -C /tmp/intel-sgx-ssl/Linux/sgx/test_app/ all
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make -f sgx_u.mk LINUX_SGX_BUILD=0 all
make[3]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
GEN  =>  app/TestEnclave_u.c
CC   <=  app/TestEnclave_u.c
app/TestApp.cpp: In function 'int initialize_enclave()':
app/TestApp.cpp:184:45: warning: argument to 'sizeof' in 'char* strncpy(char*, const char*, size_t)' call is the same expression as the source; did you mean to use the size of the destination? [-Wsizeof-pointer-memaccess]
  184 |         strncpy(token_path, TOKEN_FILENAME, sizeof(TOKEN_FILENAME));
      |                                             ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/string.h:495,
                 from app/TestApp.cpp:34:
In function 'char* strncpy(char*, const char*, size_t)',
    inlined from 'int initialize_enclave()' at app/TestApp.cpp:179:16:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: 'char* __builtin___strncpy_chk(char*, const char*, long unsigned int, long unsigned int)' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/TestApp.cpp: In function 'int initialize_enclave()':
app/TestApp.cpp:177:16: note: length computed here
  177 |         (strlen(home_dir)+strlen("/")+sizeof(TOKEN_FILENAME)+1) <= MAX_PATH) {
      |          ~~~~~~^~~~~~~~~~
CXX  <=  app/TestApp.cpp
LINK =>  TestApp
make[3]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make -f sgx_t.mk LINUX_SGX_BUILD=0 all
make[3]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
GEN  =>  enclave/TestEnclave_t.c
CC   <=  enclave/TestEnclave_t.c
CXX  <=  enclave/TestEnclave.cpp
CC  <=  enclave/tests/ecdhtest.c
CC  <=  enclave/tests/sha1test.c
CC  <=  enclave/tests/missing_funcs.c
CC  <=  enclave/tests/threadstest.c
CC  <=  enclave/tests/stdio_func.c
CC  <=  enclave/tests/dhtest.c
CC  <=  enclave/tests/ecdsatest.c
CC  <=  enclave/tests/rsa_test.c
CC  <=  enclave/tests/bntest.c
CC  <=  enclave/tests/sha256t.c
CC  <=  enclave/tests/ectest.c
LINK =>  TestEnclave.so
tcs_num 10, tcs_max_num 10, tcs_min_pool 1
The required memory is 22507520B.
The required memory is 0x1577000, 21980 KB.
Succeed.
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x1000000</HeapMaxSize>
    <TCSNum>10</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
</EnclaveConfiguration>
SIGN =>  TestEnclave.signed.so
make[3]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[1]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx'
make -C sgx/ test
make[1]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx'
make -C /tmp/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl/ all
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl'
/opt/intel/sgxsdk/bin/x64/sgx_edger8r --header-only --trusted /tmp/intel-sgx-ssl/Linux/sgx/../package/include//sgx_tsgxssl.edl --search-path /opt/intel/sgxsdk/include
GEN  =>  sgx_tsgxssl_t.c
ar rcs libsgx_tsgxssl.a release/tSgxSSL_api.o release/tcpu_utils.o release/tctype.o release/tmem_mgmt.o release/tpthread.o release/trand.o release/tsgxssl_version.o release/tsocket.o release/tstdio.o release/tstdlib.o release/tstring.o release/ttime.o release/tucontext.o release/tunistd.o release/bionic_localtime.o release/bionic_sscanf.o release/texceptions.o  
LINK =>  libsgx_tsgxssl.a
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_tsgxssl'
make -C /tmp/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl/ all
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/libsgx_usgxssl'
make -C /tmp/intel-sgx-ssl/Linux/sgx/test_app/ all
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make -f sgx_u.mk LINUX_SGX_BUILD=0 all
make[3]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make -f sgx_t.mk LINUX_SGX_BUILD=0 all
make[3]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make -C /tmp/intel-sgx-ssl/Linux/sgx/test_app/ test 
make[2]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make -f sgx_u.mk test
make[3]: Entering directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[3]: *** [sgx_u.mk:108: test] Illegal instruction (core dumped)
make[3]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[2]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx/test_app'
make[2]: *** [Makefile:38: test] Error 2
make[1]: *** [Makefile:74: test] Error 2
make: *** [Makefile:58: test] Error 2
make[1]: Leaving directory '/tmp/intel-sgx-ssl/Linux/sgx'
The command '/bin/sh -c git clone 'https://github.com/intel/intel-sgx-ssl.git'   && cd intel-sgx-ssl   && . /opt/intel/sgxsdk/environment   && git checkout lin_${SGXSSL}   && cd openssl_source   && wget -q https://www.openssl.org/source/openssl-${OPENSSL}.tar.gz   && cd ../Linux   && make SGX_MODE=SIM DESTDIR=${SGX_SSL} all test   && make install' returned a non-zero code: 2
make: *** [Makefile:170: base-dev] Error 2
vagrant@hlf-fpc:~/fabric-private-chaincode/utils/docker$ cd /tmp 
vagrant@hlf-fpc:/tmp$ git clone 'https://github.com/intel/intel-sgx-ssl.git
> '
Cloning into 'intel-sgx-ssl'...
warning: url contains a newline in its path component: https://github.com/intel/intel-sgx-ssl.git
/
fatal: credential url cannot be parsed: https://github.com/intel/intel-sgx-ssl.git
/
`

**Environment (please complete the following information):**

 - in a vagrant 20.04 image 
 - installed docker & docker-compose 
 - followed [https://github.com/hyperledger-labs/fabric-private-chaincode] Option 1: Using the Docker-based FPC Development   Environment

**Comment by mbrandenburger** [comment] 2021-03-24 10:19
It looks something goes wrong when `SGXSSL` is compiled during the docker build. Not sure why this happens.

Can you please post the docker version you are using?

I've noticed that you "checkout" the master branch, which may be sometime unstable, however, I've tried to reproduce it by following the steps you reported but on a baremetal ubuntu 20.04 - no vagrant. Unfortunately I cannot reproduce the the reported error. 

Also note that in `vagrant@hlf-fpc:/tmp$ git clone 'https://github.com/intel/intel-sgx-ssl.git` there is a `'` before the github url. Nevertheless, I think is is not related to the `SGXSSL` error you've experienced.

When you re-run `make dev` do you get the same error? Maybe cleanup your local docker registry to make sure you start from scratch.  Please let me know if this error remains.

**Comment by mbrandenburger** [comment] 2021-03-30 07:19
@joyosive Any luck?

I was compiling the FPC dev docker image including SGX SSL yesterday and I was not able to reproduce the error you reported here.

**Comment by mbrandenburger** [comment] 2021-04-12 08:50
Let's close this issue for now, if you still experience this issue, please re-open. Thank you!

**Closed by mbrandenburger** 2021-04-12 08:50 UTC
Labels: bug
