### ISSUE TITLE
tlcc still needs mrenclave.go -- not clear why or how it is used

### ISSUE THREAD

**Issue by bvavala** [hyperledger-labs/fabric-private-chaincode#107] opened 2019-07-03 21:10 UTC

**Comment by g2flyer** [comment] 2019-07-03 21:33
I assume it was intended for mutual authentication when establishing a secure channel with enclave (but not really used as currently there is no secure key-distribution but hardcoded keys?).     That said, i don't think there is necessarily a need for TLCC to authenticate the enclave: no secrecy is involved, only integrity, and that is only required for chaincode to validate TLCC?  (Maybe the protocol might for security/simplicity reason include mrenclave but TLCC would only have to verify consistency, not necessarily that it is some particular value ..)

**Comment by mbrandenburger** [comment] 2019-07-04 14:44
see also my answer in #103 regarding mrenclave and ecc.

mrenclave of TLCC should be defined in the genesis block of the channel. When a new private chaincode is install, instantiated, and registered it should indeed establish a secure channel with TLCC (currently mocked/hardcoded) and also report tlcc identity+mrenclave as part of it's attestation report.

A private chaincode (ecc) has actually no chance to verify that it communicates with a TLCC having the correct code running (as defined through mrenclave) but using the attestation report ercc-vscc is able to verify that ecc is bound to a certain tlcc.

**Comment by mbrandenburger** [comment] 2019-07-04 14:50
so I believe mrenclave.go will go away and we need another way to write it into the genesis block

**Comment by mbrandenburger** [comment] 2019-08-07 11:25
@bvavala This issue can be closed as question is answered. Please re-open if necessary and clarify question.

#131 will tackle the integration of mrenclave in the genesis block or similar.

**Closed by mbrandenburger** 2019-08-07 11:25 UTC
Labels: enhancement, question
